### ISSUE TITLE
Trying to connect to mongodb instance fails

### ISSUE THREAD

**Issue by nesdis** [SouthbankSoftware/dbkoda#1]
While connecting to a mongoDB instance i get this error:

Error: Create shell connection failed. Mongo binary might be corrupted.

Please check your mongo binary path, or define your own mongoCmd in ~/.dbKoda/config.yml (Refer to this doc for details)

connection is to localhost:27017

![image](https://user-images.githubusercontent.com/17020932/30967452-f249a274-a479-11e7-86d7-094f1c706f28.png)

**Comment by Chris2011** [comment]
Got the same issue, with Robomongo, everything works fine.

**Comment by Chris2011** [comment]
For me it is a remote host.

**Comment by christrott** [comment]
Hey nesdis and Chris2011,

Thanks for you reports. Looks like dbKoda is having trouble finding your mongo shell binary. We do try to detect it automatically, but if that fails, you can set the path to your mongo binary in the config.yml file as per the error message. (See [https://github.com/SouthbankSoftware/dbkoda#config](https://github.com/SouthbankSoftware/dbkoda#config) for details)

Firstly, make sure you're using the latest version of dbKoda (currently it is 0.7.3). If you're on the latest, you can see [https://dbkoda.useresponse.com/topic/connection-test-is-successful-connect-fails](https://dbkoda.useresponse.com/topic/connection-test-is-successful-connect-fails) for more details on possible solutions.

Please note that dbKoda does not currently support containerised mongo binaries. 

If you're still encountering issues after following these links, would you be able to post a [support bundle](https://dbkoda.useresponse.com/knowledge-base/article/how-do-i-generate-a-support-bundle) along with your config.yml file so we can further troubleshoot the issue?

Thanks,
Chris

**Comment by Chris2011** [comment]
I have 0.7.2. I checked for updatres, but it says, that my current version is up to date. So can't update. I will check the config later. Thx.
