### ISSUE TITLE
Restore Database --archive

### ISSUE THREAD

**Issue by SiyahaS** [SouthbankSoftware/dbkoda#13]
Current form of restore database functionality does not support archives. To support it we need to be able to choose archive files instead of a folder(from ui). Also --archive should be enabled if the selection is a file.

**Comment by michaeljharrison** [comment]
Hi there!

Thanks for using dbKoda and for sending us this ticket, good point! I'll make that change this week and add it to our next release. I'll update this ticket when it's available in our production release.

Cheers,
Mike from dbKoda.

**Comment by michaeljharrison** [comment]
Hi,

We've implemented support for archive with MongoDump and MongoRestore, these features will be available in our next release, which should be available before the end of the month!  Thanks again for helping us improve dbKoda.

You can subscribe on our [website](https://www.dbkoda.com), or follow us on [facebook](https://www.facebook.com/DBKodaIDE/) and [twitter](https://twitter.com/db_koda) for updates on new version releases.

Kind Regards,
Mike from dbKoda.
