### ISSUE TITLE
Import Collection

### ISSUE THREAD

**Issue by timdray** [SouthbankSoftware/dbkoda#15]
Hello,

If you use the import collection from csv and choose the headerLine check box the corresponding command is '--headerLine'. This lead to an error for me and I needed to change to '--headerline'. Not sure if this is just a problem with mongo versions. Also needed to add '--type csv'.

Thanks,

Tim

**Comment by michaeljharrison** [comment]
Hi Tim,

Sorry for the very slow response time! Thanks for using dbKoda and lodging this bug for us.
We're gonna fix this issue up in our current sprint and the feature should be fixed for the following release of the App. I'll update this ticket when that release is available.

Cheers,
Mike from dbKoda.

**Comment by michaeljharrison** [comment]
Hey Tim, 

We've just released version 1.0 of dbKoda including a fix for this issue, thanks again for bringing it to our attention. You can see the full change list for version 1.0 here: https://medium.com/dbkoda/dbkoda-1-0-is-released-w00t-45ea64f25a13

And you can get the latest version (including the fix) from www.dbkoda.com

Cheers,
Mike from dbKoda.
