### ISSUE TITLE
Test connection success but file not found when click on Connect button

### ISSUE THREAD

**Issue by geoffroy-aubry** [SouthbankSoftware/dbkoda#29]
Hi, I try to use this great tool but I'm faced with the following problem.

- dbKoda installed on Windows 10
- docker on Windows 10
- container launched on WSL (Ubuntu on Windows)

Docker config:
![docker_config](https://user-images.githubusercontent.com/1247448/44253701-b975b980-a200-11e8-98a0-c2da8b98c3aa.PNG)

Basic config:
![basic_config](https://user-images.githubusercontent.com/1247448/44253712-c1cdf480-a200-11e8-8cb2-108f62d648dc.PNG)

I try to connect to a MongoDB in docker, and test connection is a success:
![test_cnx_success](https://user-images.githubusercontent.com/1247448/44253730-ceeae380-a200-11e8-85c7-1db88721debe.PNG)

But when I click on Connection button I get an error:
![cnx_button](https://user-images.githubusercontent.com/1247448/44253744-dad6a580-a200-11e8-8c1b-926192b5e5d4.PNG)

Can you help me plz?
thx

**Comment by geoffroy-aubry** [comment]
I specify that the same configuration works both with Robo3T v1.2 and MongoDB Compass Comunity.

**Comment by michaeljharrison** [comment]
Hi Geoffroy, 

Sorry for the delayed response, we've had another user encounter the same issue, we'll investigate this week and see if we can find a fix for you as soon as possible :)

Kind Regards,
Mike from dbKoda.

**Comment by michaeljharrison** [comment]
Hi Geoffroy,

We think we may have solved this issue. Here's a link to a pre-release version of the application, we'd love it if you could give this version a try and let us know if your problem is solved.

https://github.com/SouthbankSoftware/dbkoda/releases/tag/1.1rc8

**Note**: We can't currently support Docker Edge (Dockers beta version) on Windows so that may cause further problems if you're using Docker Edge instead of regular docker.

Kind Regards,
Mike from dbKoda.

**Comment by geoffroy-aubry** [comment]
Thx for your response. I try this new version, but not worked. Test still succesfull, but Connect button in error : "Error: Failed to create Mongo shell. Please check your Mongo shell settings in Config panel or refer to this doc for details".

Mongo binary path: "C:\Program Files\Docker\Docker\resources\bin\docker.exe" exec -t mongo-server mongo
Works well in my console.

**Comment by guiguan** [comment]
Hi Geoffroy,

We have pushed a fix for the new issue. Would you mind trying the new build in https://github.com/SouthbankSoftware/dbkoda/releases/tag/1.1rc9 once again? Sorry for the troublesome :P

Thanks,
Guan

**Comment by geoffroy-aubry** [comment]
Thanks, it works! :)
