### ISSUE TITLE
error "this.text.toLowerCase is not a function"

### ISSUE THREAD

**Issue by LiboDing** [SouthbankSoftware/dbkoda#3]
After successfully login(confirmed from Query console), I got the error as blow:
```
TypeError: this.text.toLowerCase is not a function
    at e.value (app.803ff66….js:140)
    at e.value (app.803ff66….js:140)
    at e.value (app.803ff66….js:66)
    at C (app.803ff66….js:20)
    at e.n (app.803ff66….js:20)
    at e.value (app.803ff66….js:66)
    at C (app.803ff66….js:20)
    at e.n (app.803ff66….js:20)
    at app.803ff66….js:140
    at C (app.803ff66….js:20)
```
In the mean while, Topology Window shows "Loading topology..."

dbkoda version: Version 0.8.0 (0.8.0.80)
macOS version: 10.12.6

Thanks for your hard working, best wishes!

**Comment by michaeljharrison** [comment]
Hi there!

Firstly thanks for trying dbKoda, we're working on your issue now, but we're having some trouble reproducing it. If possible could you post or send us through your support bundle that will include some app logs we can use to diagnose the issue.
You can generate a support bundle using the little "!" button in the bottom right corner of the screen.
More details about generating a support bundle can be found at this FAQ: https://dbkoda.useresponse.com/knowledge-base/article/how-do-i-generate-a-support-bundle

Kind Regards,
Michael from dbKoda.

**Comment by LiboDing** [comment]
@michaeljharrison I have send an email to support@dbKoda.com which contain "Support Bundle"!

**Comment by michaeljharrison** [comment]
Hey there, due to an embarrassing mistake by myself, that email won't work right now, could you instead email that bundle to me directly at:

> Mike@Southbanksoftware.com

Sorry for the inconvenience!
