### ISSUE TITLE
Does not connect to mongo running on docker

### ISSUE THREAD

**Issue by girias** [SouthbankSoftware/dbkoda#33]
This is an env path issue in macOS's production build. Read the support docs for the below workaround. Please fix this in the production build.

Workaround:
• replace all `docker run` with the full path to docker, e.g. `/usr/local/bin/docker run`, in the `config.yml`

**Comment by michaeljharrison** [comment]
Hey there,

Thanks for finding this issue and a work around, we've released a new version of the product that we think includes a fix for this by default. The newest release is available at dbkoda.com

Kind Regards,
Mike from dbKoda.
