### ISSUE TITLE
How can i connect atlassian with +srv

### ISSUE THREAD

**Issue by mustafa-colakoglu** [SouthbankSoftware/dbkoda#39]
I cant find **Protocol** option in **Basic Connection tab** . Can you help me?

Thanks

**Comment by michaeljharrison** [comment]
Hey there,

We've added a protocol option in our latest release, you can download that release from dbkoda.com. You'll find the protocol option at the top of the basic connection tab.

Kind Regards,
Mike from dbKoda.

**Comment by mustafa-colakoglu** [comment]
Thanks.

Good works.
