### ISSUE TITLE
explain() does not support filters with ISODate()

### ISSUE THREAD

**Issue by ebarault** [SouthbankSoftware/dbkoda#4]
running `explain()` on this query returns the following error:
**"Failed to parse explain output, make sure to highlight entire statement"**

```
db.mydb
  .explain("queryPlanner")
  .find({
    data: {
      $in: [
        "38029B",
        "3807FA",
        "3808FA",
        "380EBA",
        "3815BA",
        "382A9A",
        "394A62",
        "394A63",
        "3C1215",
        "3C127A"
      ]
    },
    ts: { $gte: ISODate("2017-11-24T16:12:38Z") }
  });
```

it works when removing the filter `ts: { $gte: ISODate("2017-11-24T16:12:38Z") }`.

mongodb version is 3.4

**Comment by gharriso** [comment]
Hi Eric,

Sorry for the delay in replying.  We spent a bit of time trying to reproduce this and have found a scenario that might be related, athough I'm not sure how ISODate() interacts.  

The problem occurs on Windows only.  If you are on another platform then I'm barking up the wrong tree.  If you execute your script in our editor and see no output, could you try either:
1) Moving explain() from BEFORE the find() to AFTER the find(), or
2) adding a .next() to the end of the statement. 

So the workarounds we are looking at are:
```db.foo.find().explain('queryPlanner')```
or 
```db.foo.explain(queryPlanner).find().next()```

If either of these fixes work, then we at least understand a bit of what is going on.

What seems to be happening is that on windows only, the node pseudo terminal driver is having trouble interacting with the mongo shell when an explain cursor is opened.  We think the mongo shell might be opening a read channel to the PTY which is preventing the output coming back.

explain() before the find() returns a cursor, while explain() after the find returns JSON.  Next() in conjunction with the explain() cursor returns JSON as well.  

We're going to change our internal code to issue the next() and thus avoid the cursor/pty/windows bug in the next release.  

Does any of that make sense?  I know it all seems a bit wierd and still might have nothing to do with your specific issue

Thanks,
Guy
