### ISSUE TITLE
Indicate more precisely where the Password store is

### ISSUE THREAD

**Issue by dandv** [SouthbankSoftware/dbkoda#45]
As a new user, I had some trouble following this prompt:

> Tip: To avoid seeing this prompt every time you connect, you can setup a password store in Preferences

File -> Preferences toggles the left sidebar. The prompt could say, "Config -> General"

**Comment by michaeljharrison** [comment]
Hey,

Thanks for taking the time to give us this feedback, I'll update that prompt and it will be in the next release :)

Kind Regards,
Mike from dbKoda.

**Comment by Charuru** [comment]
Don't think this is fixed yet.
