### ISSUE TITLE
Typo on the landing page? "administration on commands"

### ISSUE THREAD

**Issue by dandv** [SouthbankSoftware/dbkoda#49]
> One-click access to MongoDB administration on commands.

**Comment by dandv** [comment]
Also, "seperate" at https://dbkoda.useresponse.com/knowledge-base/article/what-is-the-architecture-of-dbkoda

**Comment by michaeljharrison** [comment]
Hey,

Sorry for the slow response time and thank you for catching this one, I'll fix this one up now.

Kind Regards,
Mike from dbKoda.
