### ISSUE TITLE
Output. No scroll on x axis in table view

### ISSUE THREAD

**Issue by AtomicCons** [SouthbankSoftware/dbkoda#5]
Love it so far. Good work.

Issue: When I find my collection, I can scroll horizontally in the raw view, but in a table view I have no horizontal scroll.
example code:`db.getSiblingDB("testDB").getCollection("testCollection").find(
  {  },    
  {  });
`
Expected result: I expect to be able to scroll horizontally.

Version 0.8.1 on Linux

**Comment by michaeljharrison** [comment]
Hi,

Thanks for using the App and giving us feedback, it's invaluable. Looks like I made a silly mistake in some of the styling which caused the scrollbar to become hidden on different display sizes. I've made a fix for this and it will be included on our next release some time near the end of this week.

Thanks again,
Michael from dbKoda.
