### ISSUE TITLE
Outdated connection edit screenshot

### ISSUE THREAD

**Issue by dandv** [SouthbankSoftware/dbkoda#50]
At https://dbkoda.useresponse.com/knowledge-base/article/how-do-i-connect-to-a-replica-set

I actually would prefer that one if it could come back from the dead versions :)

**Comment by michaeljharrison** [comment]
Hey,

Thanks I'll update that documentation today.
We'll have a think about how we can improve upon that new screen as well.

Kind Regards,
Mike from dbKoda.
