### ISSUE TITLE
Icon Broken When On Taskbar In Windows 10

### ISSUE THREAD

**Issue by MaxLFarrell** [SouthbankSoftware/dbkoda#6]
This is the icon that shows pinned in the taskbar:
![image](https://user-images.githubusercontent.com/11714575/34682608-669e39b2-f46d-11e7-9ffd-c64c0597be30.png)
While this is the icon that shows up in the start menu:
![image](https://user-images.githubusercontent.com/11714575/34682648-8e75603c-f46d-11e7-8bc0-6d6107b7eac1.png)

**Comment by michaeljharrison** [comment]
Hi Max.

Thanks for reporting this issue, we've added this fix to our master branch and will be releasing it some time soon as well as in our nightly builds.

Kind Regards,
Mike from dbKoda.

**Comment by dandv** [comment]
I see the generic "no icon" icon on Ubuntu 18.04 after executing the appImage and choosing the desktop integration option:

![image](https://user-images.githubusercontent.com/33569/59908996-4fa3de80-93d4-11e9-9917-bc65b771cf3a.png)

The correct icon does appear in the search overlay:

![image](https://user-images.githubusercontent.com/33569/59908955-356a0080-93d4-11e9-986d-ffeff65b6167.png)
