### ISSUE TITLE
kerberos authentication

### ISSUE THREAD

**Issue by imran9m** [SouthbankSoftware/dbkoda#9]
Amazing UI. Does this support kerberos authentication or is it planned in road map?. Please advise.

**Comment by gharriso** [comment]
Thanks!  We definitely have Kerberos and LDAP authentication support in the roadmap.  Any suggestions or special requests for that feature would be very welcome!

**Comment by demesew** [comment]
Is this feature released ?

**Comment by gharriso** [comment]
I'm sorry, we have not implemented this.  dbKoda is still supported but is no longer under active development.  We're not planning new features at this time.
