### ISSUE TITLE
dbkoda Status

### ISSUE THREAD

**Issue by CyberCyclone** [SouthbankSoftware/dbkoda#98]
I'm just wondering what the status of dfkoda is? It looks like with the lack of updates that it's been abandoned.

**Comment by gharriso** [comment]
Hi,

Yes you are right, there's no active maintenance on dbKoda from the original team, many of whom have moved on.  The project is open source, so its possible that someone could take an interest, but not so far :-)

Is there any specific feature you are looking for.  I know that the product works fine against MongoDB 5.0 

Guy

**Comment by CyberCyclone** [comment]
I was just curious as it looks like a good application. I'm just cautious of projects that aren't maintained anymore.
